### PR TITLE
Improve memory utilization in the pure Java path

### PR DESCRIPTION
**Pull request by karlthepagan**
This improves the general case by allocating small re-used primitive arrays and passing them up the stack into blockmix_salsa8 and salsa20_8. Unfortunately even jdk7 doesn't seem to stack allocate these. Taking this one step further I make all major buffers class fields for a near constant memory profile.

Also fixed the exceptions thrown when running on Windows.

Here is a "bad case" performance difference, measured over loops of 10 averaged in runs of 50 on i7-3930K which shows gains as little as 2-3%. It's possible to create N,r,p combinations like 256,16,1 which greatly exaggerate the performance difference.

columns: N, r, p, ave(50) nanos per invocation, ave(50) bytes delta per loop of 10

Round 1

8192    8       1       7.677132172E7   4.802926571428572E7
8192    9       1       8.593538972E7   5.843984088888889E7
8192    10      1       9.526296554E7   6.4078846666666664E7
8192    11      1       1.0436935362E8  5.68130032E7
16384   8       1       1.501082958E8   6.402281548387097E7
16384   9       1       1.6824245094E8  9.790573938461539E7
16384   10      1       1.871972998E8   1.1331258633333333E8
16384   11      1       2.0516909732E8  1.4749913933333334E8
32768   8       1       2.9725410802E8  1.3370965007407407E8
32768   9       1       3.3364132114E8  1.43921864E8
32768   10      1       3.7131039344E8  1.539255297142857E8
32768   11      1       4.0709769344E8  2.3783391292307693E8

Round 2 - extract int arrays B32, x to parent blockmix_salsa8
driving down memory pressure

8192    8       1       7.541511396E7   10606.56
8192    9       1       8.39292394E7    213994.44897959183
8192    10      1       9.383809952E7   2207950.6666666665
8192    11      1       1.0252205956E8  3988968.0

Round 3 - extract arrays X, B32, x to parent smix
further driving down memory pressure

8192    8       1       7.567288484E7   929608.6857142857
8192    9       1       8.426645256E7   209807.2
8192    10      1       9.396060928E7   218558.16666666666
8192    11      1       1.072375194E8   209822.72
16384   8       1       1.4782262128E8  6826663.0
16384   9       1       1.6573762662E8  419523.04

Round 4 - extract working arrays B, XY, V into class fields
very close to a constant memory profile

8192    8       1       7.534449092E7   104.16326530612245
8192    9       1       8.486543134E7   46.53061224489796
8192    10      1       9.311034794E7   53.06122448979592
8192    11      1       1.0058963958E8  46.53061224489796
16384   8       1       1.474089465E8   46.53061224489796
16384   9       1       1.6655495584E8  46.53061224489796
16384   10      1       1.8330988716E8  46.53061224489796
16384   11      1       1.9819719774E8  46.53061224489796
32768   8       1       2.9227427122E8  46.53061224489796
32768   9       1       3.3014280414E8  46.53061224489796
32768   10      1       3.6368373274E8  46.53061224489796
32768   11      1       3.934064224E8   46.53061224489796

### CODE REVIEW

**Comment by wg** [comment]
Hi Karl,

Thanks for the pull request, and the bug report regarding initialization failure on unsupported platforms! I've released version 1.2.1 which fixes the bug in a different way.

Unfortunately I cannot accept your commit because it conflicts with some other work I'm doing, and I don't intend to support long-lived instances of the SCrypt class in this manner.

For performance you should definitely look into taking advantage of the native C implementation, in my tests it's about 4x faster than the pure Java version and only allocates the final output byte[] on the Java heap.

-Will

**Comment by karlthepagan** [comment]
Thanks very much for looking at the pull and providing feedback on this.

Most of the performance gain comes from dredging X, B32, and x up into the smix method. If you can accomplish anything like that it results in much less memory pressure on the JVM. Unfortunately even jdk7 doesn't handle these as non-escaping references so they end up showing as heap allocations, making an impact on total system memory measurements and performance.

This would be a very important improvement for embedded devices which cannot use native code. (for example silly things like Android tarsnap or litecoin clients)

From what I can see, creating all the buffers inside smix will still allow you to multithread the java implementation and execute each p run simultaneously.

I completely understand your reasoning on the SCrypt instancing and I went back to run some tests to make sure that instancing didn't slow down my cases, but unfortunately it did! I don't want to force anyone to hold object instances to avoid a slowdown. Please disregard that part and consider moving all buffer allocation up into smix. I can update this pull request if we can find consensus.

**Comment by wg** [comment]
Thanks for the suggestion! I benchmarked moving all allocation up to the scryptJ method, and it was indeed ~10% faster on 1.6 (Mac OS X 10.7, 64-bit JVM, build 1.6.0_29-b11-402-11M3527). Surprisingly however doing that results in a 10% slowdown on 1.7 (build 1.7.0-ea-b220).

These changes won't help the typical case on a client platform like Android because usually you'd only invoke it once, to derive a key from a password. However server performance is a concern as many concurrent requests may need to be processed efficiently, so I wouldn't want to reduce performance on Java 1.7.

Of course the litecoin use case is a bit different. You've interested me in attempting to build the native library for Android! I'll try to find some time in the near future.

**Comment by karlthepagan** [comment]
Thanks, I'll check my results on jdk7.

I've got a rooted N1 that I can help test with.

**Comment by wg** [comment]
Ok! I've improved the shared library build process and added the non-SSE2 C implementation of scrypt. It builds cleanly with the NDK and looks good on my Nexus S: with params N = 16384, r = 8, p = 1 the native implementation is about 13x faster.

**Pull request closed without merging**
